AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'config.ru'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'
Style/Documentation:
  Enabled: false